name: Update publication list

on:
  push:
    paths:
    - '_scripts/bibgen.py'
    - '_data/custom_bib.yml'
    - '.github/workflows/update_pub.yml'
  schedule:
    - cron: '0 10 * * 1'  # at 10am every Monday

jobs:
  update-publication-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Cache Python packages
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - name: Set up Python 3
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Update publication list
      id: main
      run: |
        export ADS_API_TOKEN=${{ secrets.ADS_API_TOKEN }}
        python _scripts/bibgen.py
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v4
    #   with:
    #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #     token: ${{ secrets.PAT }}
    #     commit-message: update publication list
    #     delete-branch: true
    #     title: "[bot] publication list update"
    #     body: |
    #        This is an auto-generated PR to update the publication list.
    #     branch: actions/update-publication-list
    #     labels: 'auto-update-pubs'
    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        echo "ðŸ”§ Git configured."

    - name: Commit and push if changed
      run: |
        git add _bibliography/mypapers.bib
        git add _includes/ads_citation.md
        git add _includes/ads_h.md
        git diff --staged --quiet || (
          echo "ðŸ“¤ Committing and pushing changes..."
          git commit -m "Update ADS publications"
          git push
        )